# Generated by Django 5.2.8 on 2025-12-11 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SessionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workshop_id", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("capacity_max", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("announced", "Announced"),
                            ("published", "Published"),
                            ("full", "Full"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
            },
        ),
        migrations.CreateModel(
            name="RegistrationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled_by_user", "Cancelled by user"),
                            ("cancelled_by_organizer", "Cancelled by organizer"),
                            ("attended", "Attended"),
                            ("no_show", "No show"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "session_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="django_app.sessionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "registrations",
            },
        ),
    ]
