# Generated by Django 5.2.8 on 2025-12-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrationmodel",
            old_name="session_id",
            new_name="session",
        ),
    ]
